apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations: {}
  labels:
    app: sip-proxy
  name: sip-proxy
  namespace: default
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: sip-proxy
  template:
    metadata:
      labels:
        app: sip-proxy
    spec:
      containers:
        - image: vikingvoip/sip-proxy
          name: sip-proxy
          securityContext:
            privileged: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        application: proxy
