apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations: {}
  labels:
    app: sip-proxy
  name: sip-proxy
  namespace: default
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: sip-proxy
  #strategy:
  #  rollingUpdate:
  #    maxSurge: 0
  #    maxUnavailable: 1
  #  type: RollingUpdate
  template:
    metadata:
      labels:
        app: sip-proxy
    spec:
      containers:
        - image: vikingvoip/sip-proxy
          name: sip-proxy
          securityContext:
            privileged: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        application: proxy
