apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations: {}
  labels:
    app: sip-b2bua
  name: sip-b2bua
  namespace: default
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: sip-b2bua
  template:
    metadata:
      labels:
        app: sip-b2bua
    spec:
      containers:
        - image: vikingvoip/sip-b2bua
          imagePullPolicy: Always
          volumeMounts:
          - name: fslogs
            mountPath: /fslogs
          - name: efs
            mountPath: /efs
          name: sip-b2bua
          securityContext:
            privileged: true
      volumes:
      - name: fslogs
        hostPath:
          path: /var/log/freeswitch
          type: DirectoryOrCreate
      - name: efs
        hostPath:
          path: /efs
          type: DirectoryOrCreate
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        application: b2bua
      