
global:
  datacenter: voip-full
  name: consul

ui:
  replicas: 1
  service:
    enabled: true
    type: 'LoadBalancer'
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
#  nodeSelector: 
#    application: "support"

server:
  replicas: 3
#  nodeSelector: |
#    application: "support"

client:
  enabled: false
  extraConfig: |
    {"advertise_reconnect_timeout": "15m"}
