
global:
  datacenter: voip-full
  name: consul

ui:
  replicas: 1
  service:
    enabled: true
    type: 'LoadBalancer'
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
#  nodeSelector: 
#    application: "support"

server:
  enabled: "-"
  image: null
  replicas: 3
  bootstrapExpect: 3 # Should <= replicas count

  # storage and storageClass are the settings for configuring stateful
  # storage for the server pods. storage should be set to the disk size of
  # the attached volume. storageClass is the class of storage which defaults
  # to null (the Kube cluster will pick the default).
#  storage: 10Gi
  storageClass: null
  nodeSelector: |
    application: "support"

client:
  enabled: false
  extraConfig: |
    {"advertise_reconnect_timeout": "15m"}
